# Board:
#
#   [0|<-( )] [1|<-( )]

{
 'game_a': {'rewards': [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            'players': ['Player 2', 'Player 2', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic'],
            'transition_list': [
                [('Green', 2), ('Yellow', 4)],
                [('Green', 3), ('Yellow', 5)],
                [('Down', 9)],
                [('Down', 9)],
                [('Left', 7)],
                [('Left', 6)],
                [(1, 0)],
                [(1, 1)],
                [(1, 8)],
                [(1, 9)]],
            'final_states': [9]},
 'game_b': {'rewards': [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            'players': ['Player 2', 'Player 2', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic'],
            'transition_list': [
                [('Green', 2), ('Yellow', 4)],
                [('Green', 3), ('Yellow', 5)],
                [('Down', 8)],
                [('Down', 9)],
                [('Left', 10)],
                [('Left', 11)],
                [(1, 0)],
                [(1, 1)],
                [(0.1, 6), (0.9, 15)],
                [(0.1, 7), (0.9, 15)],
                [(0.1, 6), (0.9, 7)],
                [(0.1, 7), (0.9, 6)],
                [(0.1, 6), (0.9, 7)],
                [(0.1, 7), (0.9, 6)],
                [(1, 14)],
                [(1, 15)]],
            'final_states': [15]},
 'game_c': {'rewards': [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            'players': ['Player 2', 'Player 2', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic'],
            'transition_list': [
                [('Green', 16), ('Yellow', 18)],
                [('Green', 17), ('Yellow', 19)],
                [('Down', 10)],
                [('Down', 11)],
                [('Left', 12)],
                [('Left', 13)],
                [('Down', 10), ('Left', 12)],
                [('Down', 11), ('Left', 13)],
                [(1, 0)],
                [(1, 1)],
                [(0.1, 8), (0.9, 21)],
                [(0.1, 9), (0.9, 21)],
                [(0.1, 8), (0.9, 9)],
                [(0.1, 9), (0.9, 8)],
                [(0.1, 8), (0.9, 9)],
                [(0.1, 9), (0.9, 8)],
                [(0.5, 6), (0.5, 2)],
                [(0.5, 7), (0.5, 3)],
                [(0.5, 6), (0.5, 4)],
                [(0.5, 7), (0.5, 5)],
                [(1, 20)],
                [(1, 21)]],
            'final_states': [21]}
}
