# Board:
#
#   [0|<-( )] [0|->(X)] [1|->( )]
#   [1|<-(X)] [0|<-( )] [0|<>(X)]
#   [2|<-( )] [1|->( )] [3|<>(X)]

{'game_a': {'rewards': [0, 0, 1, 1, 0, 0, 2, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            'players': ['Player 2', 'Player 2', 'Player 2', 'Player 2', 'Player 2', 'Player 2', 'Player 2', 'Player 2', 'Player 2', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Player 1', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic', 'Probabilistic'],
            'transition_list': [
                [('Red', 9), ('Yellow', 18)],
                [('Red', 10), ('Yellow', 19)],
                [('Red', 11), ('Yellow', 20)],
                [('Red', 12), ('Yellow', 21)],
                [('Red', 13), ('Yellow', 22)],
                [('Red', 14), ('Yellow', 23)],
                [('Red', 15), ('Yellow', 24)],
                [('Red', 16), ('Yellow', 25)],
                [('Red', 17), ('Yellow', 26)],
                [('Down', 30)],
                [('Down', 31)],
                [('Down', 32)],
                [('Down', 33)],
                [('Down', 34)],
                [('Down', 35)],
                [('Down', 37)],
                [('Down', 37)],
                [('Down', 37)],
                [('Left', 29)],
                [('Right', 29)],
                [('Right', 27)],
                [('Left', 32)],
                [('Left', 30)],
                [('Left', 31), ('Right', 30)],
                [('Left', 35)],
                [('Right', 35)],
                [('Left', 34), ('Right', 33)],
                [(1, 0)],
                [(0.1, 36), (0.9, 1)],
                [(1, 2)],
                [(0.1, 36), (0.9, 3)],
                [(1, 4)],
                [(0.1, 36), (0.9, 5)],
                [(1, 6)],
                [(1, 7)],
                [(0.1, 36), (0.9, 8)],
                [(1, 36)],
                [(1, 37)]],
            'final_states': [37]},
}
